#############################################################################
# Makefile for building: bin/MatriXMiX.app/Contents/MacOS/MatriXMiX
# Generated by qmake (3.1) (Qt 5.12.1)
# Project:  MatriXMiX.pro
# Template: app
# Command: /Users/maximeolivie/Qt/5.12.1/clang_64/bin/qmake -o Makefile MatriXMiX.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/Users/maximeolivie/Qt/5.12.1/clang_64/lib/QtGui.framework/Headers -I/Users/maximeolivie/Qt/5.12.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/Applications/Xcode10.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/Applications/Xcode10.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/macx-clang -F/Users/maximeolivie/Qt/5.12.1/clang_64/lib
QMAKE         = /Users/maximeolivie/Qt/5.12.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/maximeolivie/Qt/5.12.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/maximeolivie/Qt/5.12.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MatriXMiX1.0.0
DISTDIR = /Users/maximeolivie/Documents/Licence_informatique/L2/Semestre_2/LIFAP4/MatriXMiX/obj/MatriXMiX1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/maximeolivie/Qt/5.12.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/maximeolivie/Qt/5.12.1/clang_64/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/Matrix.cpp \
		src/VectorX.cpp \
		src/Polynomial.cpp \
		src/Fraction.cpp \
		src/MatriXMiXTXT.cpp \
		src/MatrixLibrary.cpp 
OBJECTS       = obj/main.o \
		obj/Matrix.o \
		obj/VectorX.o \
		obj/Polynomial.o \
		obj/Fraction.o \
		obj/MatriXMiXTXT.o \
		obj/MatrixLibrary.o
DIST          = /Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/qdevice.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/device_config.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/unix.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/mac.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/macx.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/clang.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/qconfig.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/default_post.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/mac.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/resources.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/moc.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/yacc.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/lex.prf \
		MatriXMiX.pro src/Matrix.h \
		src/VectorX.h \
		src/Polynomial.h \
		src/Fraction.h \
		src/MatriXMiXTXT.h \
		src/MatrixLibrary.h src/main.cpp \
		src/Matrix.cpp \
		src/VectorX.cpp \
		src/Polynomial.cpp \
		src/Fraction.cpp \
		src/MatriXMiXTXT.cpp \
		src/MatrixLibrary.cpp
QMAKE_TARGET  = MatriXMiX
DESTDIR       = bin/
TARGET        = bin/MatriXMiX.app/Contents/MacOS/MatriXMiX

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx10.14
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/maximeolivie/Documents/Licence_informatique/L2/Semestre_2/LIFAP4/MatriXMiX/MatriXMiX.pro


include /Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

bin/MatriXMiX.app/Contents/MacOS/MatriXMiX:  $(OBJECTS)  
	@test -d bin/MatriXMiX.app/Contents/MacOS/ || mkdir -p bin/MatriXMiX.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MatriXMiX.pro /Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/macx-clang/qmake.conf /Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/qdevice.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/device_config.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/unix.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/mac.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/macx.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/clang.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/qconfig.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/default_post.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/mac.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/resources.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/moc.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/yacc.prf \
		/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/lex.prf \
		MatriXMiX.pro \
		/Users/maximeolivie/Qt/5.12.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/maximeolivie/Qt/5.12.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile MatriXMiX.pro
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/spec_pre.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/qdevice.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/device_config.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/unix.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/mac.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/macx.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/sanitize.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/gcc-base.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/clang.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/common/clang-mac.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/qconfig.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/modules/qt_lib_zlib_private.pri:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt_functions.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt_config.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/sdk.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/toolchain.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/default_pre.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/resolve_config.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/default_post.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/default_post.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/mac.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/warn_on.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qt.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/resources.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/moc.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/unix/opengl.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/unix/thread.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/qmake_use.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/file_copies.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/rez.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/testcase_targets.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/exceptions.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/yacc.prf:
/Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/lex.prf:
MatriXMiX.pro:
/Users/maximeolivie/Qt/5.12.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/maximeolivie/Qt/5.12.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MatriXMiX.pro

qmake_all: FORCE

bin/MatriXMiX.app/Contents/PkgInfo: 
	@test -d bin/MatriXMiX.app/Contents || mkdir -p bin/MatriXMiX.app/Contents
	@$(DEL_FILE) bin/MatriXMiX.app/Contents/PkgInfo
	@echo "APPL????" > bin/MatriXMiX.app/Contents/PkgInfo
bin/MatriXMiX.app/Contents/Resources/empty.lproj: 
	@test -d bin/MatriXMiX.app/Contents/Resources || mkdir -p bin/MatriXMiX.app/Contents/Resources
	@touch bin/MatriXMiX.app/Contents/Resources/empty.lproj
	
bin/MatriXMiX.app/Contents/Info.plist: 
	@test -d bin/MatriXMiX.app/Contents || mkdir -p bin/MatriXMiX.app/Contents
	@$(DEL_FILE) bin/MatriXMiX.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,Polywaves.MatriXMiX,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},Polywaves.MatriXMiX,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,MatriXMiX,g" -e "s,@LIBRARY@,MatriXMiX,g" -e "s,\$${EXECUTABLE_NAME},MatriXMiX,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/macx-clang/Info.plist.app >bin/MatriXMiX.app/Contents/Info.plist

all: Makefile \
		bin/MatriXMiX.app/Contents/PkgInfo \
		bin/MatriXMiX.app/Contents/Resources/empty.lproj \
		bin/MatriXMiX.app/Contents/Info.plist bin/MatriXMiX.app/Contents/MacOS/MatriXMiX

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Matrix.h src/VectorX.h src/Polynomial.h src/Fraction.h src/MatriXMiXTXT.h src/MatrixLibrary.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Matrix.cpp src/VectorX.cpp src/Polynomial.cpp src/Fraction.cpp src/MatriXMiXTXT.cpp src/MatrixLibrary.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r bin/MatriXMiX.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /Users/maximeolivie/Qt/5.12.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

obj/main.o: src/main.cpp src/MatriXMiXTXT.h \
		src/MatrixLibrary.h \
		src/Matrix.h \
		src/VectorX.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/Matrix.o: src/Matrix.cpp src/Matrix.h \
		src/VectorX.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Matrix.o src/Matrix.cpp

obj/VectorX.o: src/VectorX.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/VectorX.o src/VectorX.cpp

obj/Polynomial.o: src/Polynomial.cpp src/VectorX.h \
		src/Polynomial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Polynomial.o src/Polynomial.cpp

obj/Fraction.o: src/Fraction.cpp src/Fraction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Fraction.o src/Fraction.cpp

obj/MatriXMiXTXT.o: src/MatriXMiXTXT.cpp src/MatriXMiXTXT.h \
		src/MatrixLibrary.h \
		src/Matrix.h \
		src/VectorX.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MatriXMiXTXT.o src/MatriXMiXTXT.cpp

obj/MatrixLibrary.o: src/MatrixLibrary.cpp src/MatrixLibrary.h \
		src/Matrix.h \
		src/VectorX.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MatrixLibrary.o src/MatrixLibrary.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

